### ISSUE TITLE
Missing plus in catalog's Slotted P equation

### ISSUE THREAD

**Issue by paulapatience** [jwf23/Equation-based-Lattice-Structure-Dataset#3]
The equation for the Slotted P surface in the catalog contains a typo: $-2(C_{2x}+C_{2y}C_{2z})$ should be $-2(C_{2x}+C_{2y}+C_{2z})$ instead.

**Comment by jwf23** [comment]
Hi Paul, you are correct. Silven Stallard from the University of Kansas pointed this out to me also and I forgot to update the repository with the correction. I am pushing an updated pdf now. I also confirmed that the correct equation was used for the modeling and analysis of the lattice.

Thanks!
